### ISSUE TITLE
level 2 should not box for "might"

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/MarkovChainDemo#13]
In the unstable branch, click on "might" in pane 2. In pane 4 you see `might --> have --> [been (0.5), not (0.5)]`

Level 2 is drawn as a box with two items. This is unnecessary; we have plenty of room to draw 2 nodes at level 2 instead of collecting them into a box.

**Comment by thetechdude124** [comment]
Done.

**Comment by thetechdude124** [comment]
Fixed.

**Comment by touretzkyds** [comment]
Click on "must" and get "must" --> "be" --> box with four entries. We don't need to box this; there is plenty of room to make separate arrows. Start boxing at 5 or more entries.

**Comment by touretzkyds** [comment]
Verified fixed.
