### ISSUE TITLE
pane 4 display missing an arrow

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/MarkovChainDemo#14]
Switch to a trigram model and change the text to "about as old as and about as tall as". Rebuild the dictionary.

In pane 2, click on "as tall". The pane 4 display is missing the arrow.

**Comment by thetechdude124** [comment]
Done.

**Comment by touretzkyds** [comment]
Click on "and about as" and the level 2 node "as tall as" is missing the big right bracket. This is a bug.

**Comment by touretzkyds** [comment]
Verified fixed.
