### ISSUE TITLE
horizontal layout in a box

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/MarkovChainDemo#24]
Load the article on "chocolate" and switch to trigram mode. Click on "a b" in pane 2. There are a lof of successors, so we get a box in pane 4. Some of the items in the box overlap each other due to insufficient horizontal spacing. Why is this happening?

**Comment by touretzkyds** [comment]
There is no longer a box in pane 4, but the vertical spacing of the four successors to "b c" is inadequate.

**Comment by touretzkyds** [comment]
The vertical spacing looks good now for "b c". But why is the right bracket spacing in level 2 so irregular?

**Comment by thetechdude124** [comment]
Right bracket spacing is based on the longest word in the previous chain.
For longer words, the bracket shifts more to the right. I can make this
fixed if you'd like?

**Comment by touretzkyds** [comment]
Looks good now.
