### ISSUE TITLE
missing probabilities

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/MarkovChainDemo#26]
Enter the following in the text box: "root a1 a21 root b1 b21". Rebuild the bigram dictionary. Select "root" in pane 2 and you get a diagram in pane 4 with no probabilities on the outgoing links from "root". Why aren't the probabilities being drawn?

**Comment by thetechdude124** [comment]
Fixed.

**Comment by touretzkyds** [comment]
Verified fixed.
