### ISSUE TITLE
choices in pane 3

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/MarkovChainDemo#4]
1. In pane 3, when in manual generation mode, show the probability next to each word; display it as a percentage, e.g., "saw 33.5%". Use one digit after the decimal point.
2. Rename the "Random Choice" button to "Computer choice"

**Comment by touretzkyds** [comment]
Skip item 2 but do item 1. Use the same format as pane 4, i.e., 0.35 instead of 35%.

**Comment by thetechdude124** [comment]
Done.

**Comment by thetechdude124** [comment]
Done for bi-grams - bug present for tri-and-tetra-grams. Resolving.

**Comment by thetechdude124** [comment]
Fixed.

**Comment by touretzkyds** [comment]
Tested and verified.
