### ISSUE TITLE
pane 1 changes

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/MarkovChainDemo#5]
1. Clicking inside the Wikipedia article name edit box should clear the prompt string.
2. Make the Wikipedia box shorter so we have room underneath it.
3. Change the Impot button to an icon.
4. Slide the "Rebuild Dictionary" and "Clear" buttons to the right to make room for a token count message.
5. Display token count as "Current text contains #### tokens".
6. If the user edits the current text, causing us to un-gray the "Rebuild dictionary" button, we should also hide the token count message. We will put it back after rebuilding the dictionary.

**Comment by thetechdude124** [comment]
Done.

**Comment by touretzkyds** [comment]
If the user makes any changes to the text in pane 1 we should also clear panes 2-4.

**Comment by thetechdude124** [comment]
Done.

**Comment by touretzkyds** [comment]
Looks good.
