### ISSUE TITLE
clearing panes before loading an article

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/MarkovChainDemo#6]
When the user loads a Wikipedia article it can take a while to download and process it. Meanwhile the user is staring at what are now stale displays in panels 2-4, but they don't know that.

What we should do in this situation: before loading and processing the Wikipedia article, clear panes 2-4.

**Comment by thetechdude124** [comment]
Done.

**Comment by touretzkyds** [comment]
This fix is wrong. The contents of panes 1-4 are being cleared as soon as the user clicks in the article name text box. Don't do that. Only clear the contents when the user confirms their selection, either by hitting Enter or pressing the Import button.

**Comment by thetechdude124** [comment]
Done.

**Comment by touretzkyds** [comment]
Fix the message in pane 3 to say "Please wait while we load the specified text..."

**Comment by touretzkyds** [comment]
Tested and verified.
